### ISSUE TITLE
Fix vulnerabilities security

### ISSUE THREAD

**Issue by kimnh-0823** [viblo-asia/echo-server#1]
As the title, please check the [network alerts](https://github.com/viblo-asia/echo-server/network/alerts) page. I have yet to be able to fix these vulnerabilities. Could you please help us!

**Comment by SuyashDeshmukh** [comment]
I would like to work on this issue. Can you please provide more details ? The network alerts page link gives a 404.

**Comment by kimnh-0823** [comment]
@SuyashDeshmukh Srr, the network alerts page is private. Let fork this repository then you will see the same page in your fork-repository. Go ahead!
